### PR TITLE
Fix footer checkbox

### PR DESCRIPTION
**Pull request by hexrcs**
@pm8008 Test it out. I see you limited the width of the brush to be 700px, should we remove the background pink and reduce the container width (65rem) to 700px?

### CODE REVIEW

**Comment by pm8008** [comment]
Great, thanks a lot!
Here's the container adjustment:
https://github.com/DHSTTOS/implementation/pull/92

**Comment by pm8008** [comment]
BTW, I'm using a fixed width for the d3 stuff, because main.attr("width") is 0, and there doesn't seem to be a straightforward way to find out what width that container has. I only found some terrible hacks that I didn't understand enough to be comfortable with using them.

**Comment by hexrcs** [comment]
@pm8008 Thanks! A little more research reveals that [`Element.getBoundingClientRect()`](https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect) is the right way to obtain the dimensions of an DOM element (returns an object, so in this case something like `main.getBoundingClientRect().width` will get you the width in pixels). 700px is totally fine, but if you'd like you can remove the hardcoded size and use `getBoundingClientRect()`. (Beware that this dim info also includes the margin, border etc. But in our case the `main` is a plain `<div />` with no styles, so `getBoundingClientRect()` should get the correct values back.)

**Comment by pm8008** [comment]
Weird: At the beginning of componentDidMount, output of console.log(this.brush.current.getBoundingClientRect()); is:

DOMRect { x: 378.79998779296875, y: 570, width: 0, height: 80, top: 570, right: 378.79998779296875, bottom: 650, left: 378.79998779296875 }

i.e. height is correct but width isn't (and note that right == left)

After executing this part:
`
let width = 700;
let heigth = 85;
[...] 
let svg = main                         
  .append('svg')                                      
  .attr('width', width)   
  .attr('height', height);;
`
the output is
DOMRect { x: 373, y: 570, width: 700, height: 80, top: 570, right: 1072, bottom: 650, left: 373 }

i.e. the width of the element gets set to the width of the newly created svg, but the height stays as it was.
*shrug*
I'll leave this as it is, i.e hardcoded.

**Comment by hexrcs** [comment]
I got it 🤦‍♂️ because it's a plain div without styles, of course it's 0 at the beginning 😂 should have make it expand to fill the parent element. But let's settle for 700px.

**Pull request merged**
